config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      registrations: 'registrations'
  }
   
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
 
  root to: 'homes#index'
  
  resources :homes, only: [:show, :index]

  resources :houses do
    resources :reservations
  end
  resources :categories, only: [:show, :index]
  resources :locations, only: [:show, :index]
  resources :profiles, only: [:show,:edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

  has_many :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :houses
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :reservation
end

app/models/house.rb
class House < ApplicationRecord
    belongs_to :user
    belongs_to :category,counter_cache:true
    has_many_attached :images

    belongs_to :category
    belongs_to :location
    has_many :reservations

    geocoded_by :localisation
    after_validation :geocode, if: :localisation_changed?
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :houses
end

app/models/notification.rb
class Notification < ApplicationRecord
    belongs_to :user
    belongs_to :recipient, class_name: "User"
    belongs_to :notifiable, polymorphic: true
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :account
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :house
    belongs_to :user
    has_many :charges
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
  after_create :create_profile
  has_many :houses       
  has_many :reservations

  has_many :notifications, foreign_key: :recipient_id

  has_one_attached :avatar
                                                                                                                                                                                                                                                                                                                                                                                                                                          
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/_background.html.erb
<div class=" background" >
        <div id="particles-js" style ='height:700px'>
     
             <h1 class='para'>Bienvenue</h1>
             <p class='para1'>Plannifier vos prochains vacances avec nous</p>
             <%= link_to "S'incrire",new_user_registration_path,class:' btn btn-outline-primary paras'  %>
             <%= link_to "Se connecter",new_user_session_path,class:' btn btn-success paras1'  %>
        </div>     
    
</div>

<script src="/javascript/packs/app.js"></script>
<script src="/javascript/packs/particles.js"></script>

app/views/layouts/_charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/_footer.html.erb
 <!-- ***** Footer Area Start ***** -->
    <footer class="footer-social-icon text-center section_padding_70 clearfix">
        <!-- footer logo -->
        <div class="footer-text">
            <h2>H. app</h2>
        </div>
        <!-- social icon-->
        <div class="footer-social-icon">
            <a target="_blank" href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiFprWm09DuAhXSUjUKHd2OCK4QFjAAegQIARAD&url=https%3A%2F%2Fwww.facebook.com%2F&usg=AOvVaw2q27ov2cpCynr72DmuSqEz"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a target="_blank" href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj_9vaE09DuAhVzElkFHVDkCGkQFjAAegQIARAD&url=https%3A%2F%2Fwww.instagram.com%2F&usg=AOvVaw1cBeRoOpMhZ3-x5M1sA3Fm"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            <a target="_blank" href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiu956J09DuAhVwGFkFHRPOAKQQFjAAegQIAhAD&url=https%3A%2F%2Ftwitter.com%2F%3Flang%3Den&usg=AOvVaw1Sd3B-_cNZOLSmhw9z2lOm"> <i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a target="_blank" href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjo3OWO09DuAhW2GFkFHTOACOkQFjAKegQICBAC&url=https%3A%2F%2Faccounts.google.com%2Flogin&usg=AOvVaw3rc2qJQnin1syHxrs_6Fur"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
        </div>
        <div class="footer-menu">
            <nav>
                <ul>
                    <li><a target="_blank" href="https://www.termsandconditionsgenerator.com/live.php?token=kHFXLOKa9eVjjfuCy9qFkjkYWhXkMhpU">Terms &amp; Conditions</a></li>
                    <li><a target="_blank" href="https://www.privacypolicygenerator.info/live.php?token=U92ka14oglE9ZsRsTk0YDFwh1VY9v44h">Privacy Policy</a></li>
                </ul>
            </nav>
        </div>
        <!-- Foooter Text-->
        <div class="copyright-text">
            <p>Copyright ©2021 Designed by <a href="https://avengers.com" target="_blank">Avengers #10</a></p>
        </div>
    </footer>
    <!-- ***** Footer Area End ***** -->

app/views/layouts/_location.html.erb
<div class='container-fluid location'>
    <div class='row' style='margin:50px'>
        
            <h1 style='margin:0 auto'>Quels destinations vous aimerez ?</h1>
            <div class="line-shape"></div>
    </div> 
  
    <div class='row'>
        <div class='col-4' style="display:flex">
            <%= image_tag('flower.jpeg',height:'150',width:'200',style:'margin:10px;border-radius:25px') %>
             <p style='margin:30px 10px 10px 10px'><%= link_to @location.first.city_name,location_path(1) %></p>
        </div>
        <div class='col-4' style="display:flex">
            <%= image_tag('car.jpeg',height:'150',width:'200',style:'margin:10px;border-radius:25px') %>
            <p style='margin:30px 10px 10px 10px'><%= link_to @location.find(2).city_name,location_path(2) %></p>
        </div>
        <div class='col-4' style="display:flex">
            <%= image_tag('images.jpeg',height:'150',width:'200',style:'margin:10px;border-radius:25px') %>
            <p style='margin:30px 10px 10px 10px'><%= link_to @location.find(3).city_name,location_path(3) %></p>
        </div>
        <div class='col-4' style="display:flex">
            <%= image_tag('car.jpeg',height:'150',width:'200',style:'margin:10px;border-radius:25px') %>
            <p style='margin:30px 10px 10px 10px'><%= link_to @location.find(4).city_name,location_path(4) %></p>
        </div>
        <div class='col-4' style="display:flex">
            <%= image_tag('kitro.jpeg',height:'150',width:'200',style:'margin:10px;border-radius:25px') %>
            <p style='margin:30px 10px 10px 10px'><%= link_to @location.find(5).city_name,location_path(5) %></p>
        </div>
        <div class='col-4' style="display:flex">
            <%= image_tag('mer.jpeg',height:'150',width:'200',style:'margin:10px;border-radius:25px') %>
            <p style='margin:30px 10px 10px 10px'><%= link_to @location.find(6).city_name,location_path(6) %></p>
        </div>
       
    </div>
</div>

<hr>

app/views/layouts/_navigation.html.erb
<!-- Preloader Start -->
<div id="preloader">
    <div class="devdap-load"></div>
</div>

<%if user_signed_in?%>
    <header class="header_area animated">      
        <div class="container-fluid">
            <div class="row align-items-center">
                
                <!-- Menu Area Start -->
                <div class="col-12 col-lg-10">
                    <div class="menu_area">
                        <nav class="navbar navbar-expand-lg navbar-light">
                            <!-- Logo -->
                            <a class="navbar-brand" href="/">H.</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ca-navbar" aria-controls="ca-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                            <!-- Menu Area -->
                            <div class="collapse navbar-collapse" id="ca-navbar">
                                <ul class="navbar-nav ml-auto" id="nav">
                                    <li class="nav-item"><a class="nav-link" href="#features">Why H. app?</a></li>
                                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                                    <%= link_to 'Houses', houses_path, class: "nav-link" %>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
                <!-- Signup btn -->
                <div class="col-12 col-lg-2" style='display:flex;justify-content:center'>

                          <div class="dropdown">
                                <a data-toggle="dropdown"> 
                                    <% if current_user.avatar.attached? %>
                                        <%= image_tag(current_user.avatar,height:"50",width:"50",style:'border-radius:50%') %>    
                                    <% else %>
                                        <%= image_tag('avatar.jpg',height:"50",width:"50",style:'border-radius:50%') %>
                                    <% end %>
                                </a>
                                <div class="dropdown-menu" style='margin-top:20px;margin-right:50px'>
                                        <p class="dropdown-item"><b>You are signed with:</b> <br> <%= current_user.name + ' ' + current_user.first_name  %> </p>
                                        <hr>
                                        <%= link_to "Dashboard", profile_path(current_user.id), class: "dropdown-item" %>
                                        <%= link_to "Modify account", edit_user_registration_path,class:"dropdown-item" %>
                                        <%= link_to "Log out", destroy_user_session_path,class:"dropdown-item" %>
                                        <div class="dropdown-divider"></div>
                                
                                </div>
                            </div>

                </div>
            </div>
        </div>
    </header>

<% else %>
<!-- ***** Header Area Start ***** -->
    <header class="header_area animated">
        <div class="container-fluid">
            <div class="row align-items-center">
                <!-- Menu Area Start -->
                <div class="col-12 col-lg-10">
                    <div class="menu_area">
                        <nav class="navbar navbar-expand-lg navbar-light">
                            <!-- Logo -->
                            <a class="navbar-brand" href="/">H.</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ca-navbar" aria-controls="ca-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                            <!-- Menu Area -->
                            <div class="collapse navbar-collapse" id="ca-navbar">
                                <ul class="navbar-nav ml-auto" id="nav">
                                    <li class="nav-item"><a class="nav-link" href="#features">Why H. app?</a></li>
                                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                                    <%= link_to 'Create house', new_house_path, class: "nav-link" %>
                                    <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
                <!-- Signup btn -->
                <div class="col-12 col-lg-2">
                    <div class="sign-up-button d-none d-lg-block">
                        <%= link_to "Register Now", new_user_registration_path %>
                    </div>
                </div>
            </div>
        </div>
    </header>
<!-- ***** Header Area End ***** -->

<% end %>

app/views/layouts/_terms.html.erb
<h2><strong>Terms and Conditions</strong></h2>

<p>Welcome to Home!</p>

<p>These terms and conditions outline the rules and regulations for the use of Home's Website, located at www.h_ome.com.</p>

<p>By accessing this website we assume you accept these terms and conditions. Do not continue to use Home if you do not agree to take all of the terms and conditions stated on this page.</p>

<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company’s terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client’s needs in respect of provision of the Company’s stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>

<h3><strong>Cookies</strong></h3>

<p>We employ the use of cookies. By accessing Home, you agreed to use cookies in agreement with the Home's Privacy Policy. </p>

<p>Most interactive websites use cookies to let us retrieve the user’s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p>

<h3><strong>License</strong></h3>

<p>Unless otherwise stated, Home and/or its licensors own the intellectual property rights for all material on Home. All intellectual property rights are reserved. You may access this from Home for your own personal use subjected to restrictions set in these terms and conditions.</p>

<p>You must not:</p>
<ul>
    <li>Republish material from Home</li>
    <li>Sell, rent or sub-license material from Home</li>
    <li>Reproduce, duplicate or copy material from Home</li>
    <li>Redistribute content from Home</li>
</ul>

<p>This Agreement shall begin on the date hereof. Our Terms and Conditions were created with the help of the <a href="https://www.termsandconditionsgenerator.com">Terms And Conditions Generator</a> and the <a href="https://www.generateprivacypolicy.com">Privacy Policy Generator</a>.</p>

<p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. Home does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of Home,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, Home shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p>

<p>Home reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</p>

<p>You warrant and represent that:</p>

<ul>
    <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>
    <li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>
    <li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>
    <li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>
</ul>

<p>You hereby grant Home a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p>

<h3><strong>Hyperlinking to our Content</strong></h3>

<p>The following organizations may link to our Website without prior written approval:</p>

<ul>
    <li>Government agencies;</li>
    <li>Search engines;</li>
    <li>News organizations;</li>
    <li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>
    <li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</li>
</ul>

<p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party’s site.</p>

<p>We may consider and approve other link requests from the following types of organizations:</p>

<ul>
    <li>commonly-known consumer and/or business information sources;</li>
    <li>dot.com community sites;</li>
    <li>associations or other groups representing charities;</li>
    <li>online directory distributors;</li>
    <li>internet portals;</li>
    <li>accounting, law and consulting firms; and</li>
    <li>educational institutions and trade associations.</li>
</ul>

<p>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of Home; and (d) the link is in the context of general resource information.</p>

<p>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party’s site.</p>

<p>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to Home. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</p>

<p>Approved organizations may hyperlink to our Website as follows:</p>

<ul>
    <li>By use of our corporate name; or</li>
    <li>By use of the uniform resource locator being linked to; or</li>
    <li>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party’s site.</li>
</ul>

<p>No use of Home's logo or other artwork will be allowed for linking absent a trademark license agreement.</p>

<h3><strong>iFrames</strong></h3>

<p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p>

<h3><strong>Content Liability</strong></h3>

<p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p>

<h3><strong>Your Privacy</strong></h3>

<p>Please read Privacy Policy</p>

<h3><strong>Reservation of Rights</strong></h3>

<p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it’s linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p>

<h3><strong>Removal of links from our website</strong></h3>

<p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</p>

<p>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p>

<h3><strong>Disclaimer</strong></h3>

<p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p>

<ul>
    <li>limit or exclude our or your liability for death or personal injury;</li>
    <li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
    <li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
    <li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
</ul>

<p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</p>

<p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    

    <!-- Title -->
    <title>H. Find Your Home NOW</title>

    <!-- Favicon -->
    <%= favicon_link_tag 'core-img/favicon.ico' %>
    
    <!-- Stylesheets -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

     

  
    
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Menu Partials -->
    <%= render 'layouts/navigation' %>
    
     <%= yield %>
    
    <!-- Footer Partials -->
    <%= render 'layouts/footer' %>

    <!-- Javascripts -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">%>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script> 
    
  </body>
</html>

app/views/layouts/my_layout.html.haml
!!!
%html{:lang => 'en'}
  %head
    - # ...
    = google_maps_api_script_tag

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>